version: '3.8'
services:
  frontend:
    image: jinyoungko/frontend:latest
    ports:
      - "8086:80"
    environment:
      - WS_BACK_URL=https://8082-coursesilv-labdockerjin-bhua2n2xmwd.ws-eu108.gitpod.io

  backend:
    image: jinyoungko/backend:latest
    ports:
      - "8082:5000"
    environment:
      - CURRENT_ENVIRONMENT=development
    volumes:
      - ./backend-logs:/app/logs
      
      



      
